# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tylerives.com
email: ct.ives@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal webpage of Tyler Ives.  Here you will find my resume and some random stuff about me that you may or
  may not find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tylerives.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ctives
instagram_username: ctives
linkedin_username:

# Build settings
sass:
  sass_dir: _sass

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - assets/scss/